version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  slack: circleci/slack@4.1

executors:
  base:
    docker:
    - image: circleci/openjdk:8-jdk
  cypress-tests:
    resource_class: large
    docker:
      - image: 908690569502.dkr.ecr.eu-west-1.amazonaws.com/cmp-stunnel:latest
        aws_auth:
          aws_access_key_id: $ECR_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY         

slack-fail-post-step: &slack-fail-post-step
  context:
    - platformintegration-api-ci-slack
  post-steps:
    - slack/notify:
        branch_pattern: .+
        event: fail
        template: basic_fail_1
        channel: C02L84WH2TZ

commands:
  install_nodejs:
    steps:
      - run:
          name: Install Node.js
          command: |
            curl -sSL "https://nodejs.org/dist/v10.21.0/node-v10.21.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v10.21.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo npm_install=6.14.11 sh
  run_npm_command_with_cache:
    parameters:
      command:
        type: string
    steps:
      - restore_cache:
          name: Restore npm cache
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: NPM install
          command: npm << parameters.command >>
      - save_cache:
          name: Save npm cache
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  install_js_dependencies_with_cache:
    steps:
      - run_npm_command_with_cache:
          command: run install-js-dependencies

  run_cypress_tests:
    steps:
      - run:
          name: Run Cypress tests
          command: |  
            ./node_modules/cypress/bin/cypress run --spec "$( circleci tests glob cypress/integration/**/*.js | circleci tests split --split-by=filesize)" --reporter cypress-circleci-reporter

                     
jobs:
  build:
    docker:
      - image: circleci/php:7.4-browsers
    steps:
      - checkout
      - install_nodejs 
   

  cypress-tests:
    machine:
      image: ubuntu-2004:202010-01
    parallelism: 3
    parameters:
        wp-version:
            type: string
            default: "latest"
    resource_class: xlarge
    steps:
    - checkout
    - attach_workspace:
          at: .   
    - run:
        name: Stunnel Config
        command: |
          echo "127.0.0.1 capi-si.newsint.co.uk" >> /etc/hosts
          echo "127.0.0.1 capi-si.cloud-newsint.co.uk" >> /etc/hosts
          echo "127.0.0.1 cmp-si-capi.cloud-newsint.co.uk" >> /etc/hosts
          echo "127.0.0.1 origin-capi-si.cloud-newsint.co.uk" >> /etc/hosts
          echo "127.0.0.1 origin-capi-uat.cloud-newsint.co.uk" >> /etc/hosts
          echo "127.0.0.1 cmp-config-si.cloud-newsint.co.uk" >> /etc/hosts
          echo "127.0.0.1 cmp-config-uat.cloud-newsint.co.uk" >> /etc/hosts
          echo "127.0.0.1 home-si.uat-thetimes.co.uk" >> /etc/hosts
          echo "127.0.0.1 home.uat-thetimes.co.uk" >> /etc/hosts
          echo "127.0.0.1 join-si.uat-thetimes.co.uk" >> /etc/hosts
          echo "127.0.0.1 join.uat-thetimes.co.uk" >> /etc/hosts
          echo "127.0.0.1 acs-uat.newsint.co.uk" >> /etc/hosts
          echo "127.0.0.1 cmptools-eks.ceng-dev.newsuk.tech" >> /etc/hosts
          echo ${STUNNEL_PSK} > /etc/stunnel/psk.txt
          chmod 600 /etc/stunnel/psk.txt    
    - run:
          name: npm install
          command: |
            npm ci
    - run:
          name: npm install day js
          command: |
            npm i dayjs
    - run:  
          name: Run Cypress tests 
          command: |  
            ./node_modules/cypress/bin/cypress run --spec "$( circleci tests glob cypress/integration/**/*.js | circleci tests split --split-by=timings | paste -sd "," -)" --reporter cypress-circleci-reporter 
    - store_artifacts:
          path: cypress/screenshots
    - store_test_results:
          path: test_results/cypress


workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          <<: *slack-fail-post-step
          filters:
            branches:
              ignore: /.*-built
      - cypress-tests:
          <<: *slack-fail-post-step
          requires:
            - build

      
