version: 2.1
orbs:
  slack: circleci/slack@4.1

slack-fail-post-step: &slack-fail-post-step
  context:
    - platformintegration-api-ci-slack
  post-steps:
    - slack/notify:
        branch_pattern: master
        event: fail
        template: basic_fail_1
        channel: C02L84WH2TZ

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

cypress_tests:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: Running cypress tests
          command: npm cy:test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots            


workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          <<: *slack-fail-post-step
          filters:
            branches:
              ignore: /.*-built
   
      
      
      
