version: 2.1
orbs:
  slack: circleci/slack@4.1
  port-forwarder: nukengprod/port-forwarder@1.0.1

slack-fail-post-step: &slack-fail-post-step
  context:
    - platformintegration-api-ci-slack
  post-steps:
    - slack/notify:
        branch_pattern: .+
        event: fail
        template: basic_fail_1
        channel: C02L84WH2TZ

commands:

  install_nodejs:
    steps:
      - run:
          name: Install Node.js
          command: |
            curl -sSL "https://nodejs.org/dist/v10.21.0/node-v10.21.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v10.21.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo npm_install=6.14.11 sh
  run_npm_command_with_cache:
    parameters:
      command:
        type: string
    steps:
      - restore_cache:
          name: Restore npm cache
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: NPM install
          command: npm << parameters.command >>
      - save_cache:
          name: Save npm cache
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  install_js_dependencies_with_cache:
    steps:
      - run_npm_command_with_cache:
          command: run install-js-dependencies

  start-port-forwarder:
        description: Start proxying to nuk-port-forwarder
        steps:
            - port-forwarder/install
            - port-forwarder/hosts:
                  hostname: api.test-thetimes.co.uk
            - port-forwarder/hosts:
                  hostname: cps-api-tnl-ci.elb.tnl-dev.ntch.co.uk
            - port-forwarder/authenticate:
                  aws_access_key_id: PORT_FORWARDER_EKS_AWS_ACCESS_KEY_ID
                  aws_secret_access_key: PORT_FORWARDER_EKS_AWS_SECRET_ACCESS_KEY
                  aws_role_arn: PORT_FORWARDER_EKS_AWS_ROLE_ARN
                  cluster_name: PORT_FORWARDER_EKS_CLUSTER_NAME
                  namespace: PORT_FORWARDER_EKS_NAMESPACE
            - port-forwarder/start        

  run_cypress_tests:
    steps:
      - run:
          name: Run Cypress tests
          command: |  
            ./node_modules/cypress/bin/cypress run --spec "$( circleci tests glob cypress/integration/**/*.js | circleci tests split --split-by=filesize)" --reporter cypress-circleci-reporter
jobs:
  build:
    docker:
      - image: circleci/php:7.4-browsers
    steps:
      - checkout
      - install_nodejs 
   

  cypress-tests:
    machine:
      image: ubuntu-2004:202010-01
    parallelism: 3
    parameters:
        wp-version:
            type: string
            default: "latest"
    resource_class: xlarge
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: npm install
          command: |
            npm ci
      - start-port-forwarder      
      - run:  
          name: Run Cypress tests 
          command: |  
            ./node_modules/cypress/bin/cypress run --spec "$( circleci tests glob cypress/integration/**/*.js | circleci tests split --split-by=filesize | paste -sd "," -)" --reporter cypress-circleci-reporter 
      - store_artifacts:
          path: cypress/screenshots
      - store_test_results:
          path: test_results/cypress



workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          <<: *slack-fail-post-step
          filters:
            branches:
              ignore: /.*-built
      - cypress-tests:
          <<: *slack-fail-post-step
          requires:
            - build